name: Testing anvil-zksync using e2e
on:
  workflow_call:

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: e2e
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: 'e2e-tests/yarn.lock'

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: anvil-zksync-${{ matrix.os }}.tar.gz
      
      - name: Start the anvil-zksync
        id: start_node
        run: |
          echo "Extracting anvil-zksync binary"
          tar -xzf anvil-zksync-${{ matrix.os }}.tar.gz
          chmod +x anvil-zksync
          echo "Starting node in background"
          ./anvil-zksync 2>&1 | tee anvil-zksync-output.log &
          echo "PID=$!" >> $GITHUB_ENV

      - name: Launch tests
        id: launch
        run: |
          echo "Run tests"
          make test-e2e

      - name: Stop the anvil-zksync and print output logs
        id: stop_node
        if: always()
        run: |
          cat anvil-zksync-output.log
          kill $PID
