name: Testing anvil-zksync against ETH spec
on:
  workflow_call:

jobs:
  spec:
    runs-on: ubuntu-latest
    name: spec
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: anvil-zksync-ubuntu-latest.tar.gz
      
      - name: Extract anvil-zksync
        id: extract_node
        run: |
          echo "Extracting anvil-zksync binary"
          tar -xzf anvil-zksync-ubuntu-latest.tar.gz
          chmod +x anvil-zksync

      - name: Build ETH spec
        id: build_eth_spec
        working-directory: ./execution-apis
        run: npm install && npm run build

      - name: Launch tests
        id: launch
        working-directory: ./spec-tests
        run: cargo test
        env:
          ANVIL_ZKSYNC_BINARY_PATH: ../anvil-zksync
